In [1]:
import xarray as xr
import numpy as np
ds = xr.Dataset()
ds["mesh2d"] = xr.DataArray(
    data=0,
    attrs={
     "cf_role": "mesh_topology",
     "long_name": "Topology data of 2D mesh",
     "topology_dimension": 2,
     "node_coordinates": "node_x node_y",
     "face_node_connectivity": "face_nodes",
    }
)
ds    

<xarray.Dataset>
Dimensions:  ()
Data variables:
    mesh2d   int64 0

In [2]:
ds = ds.assign_coords(
    node_x=xr.DataArray(
        data=np.array([0.0, 10.0, 10.0, 0.0, 20.0, 20.0]),
        dims=["node"],
    )
)
ds

<xarray.Dataset>
Dimensions:  (node: 6)
Coordinates:
    node_x   (node) float64 0.0 10.0 10.0 0.0 20.0 20.0
Dimensions without coordinates: node
Data variables:
    mesh2d   int64 0

In [3]:
ds = ds.assign_coords(
    node_y=xr.DataArray(
        data=np.array([0.0, 0.0, 10.0, 10.0, 0.0, 10.0]),
        dims=["node"],
    )
)
ds

<xarray.Dataset>
Dimensions:  (node: 6)
Coordinates:
    node_x   (node) float64 0.0 10.0 10.0 0.0 20.0 20.0
    node_y   (node) float64 0.0 0.0 10.0 10.0 0.0 10.0
Dimensions without coordinates: node
Data variables:
    mesh2d   int64 0

In [4]:
ds["face_nodes"] = xr.DataArray(
    data=np.array([
        [0, 1, 2, 3],
        [1, 4, 5, -1]
    ]),
    coords={
        "face_x": ("face", np.array([5.0, 15.0])),
        "face_y": ("face", np.array([5.0, 5.0])),
    },
    dims=["face", "nmax_face"],
    attrs={
        "cf_role": "face_node_connectivity",
        "long_name": "Vertex nodes of mesh faces (counterclockwise)",
        "start_index": 0,
        "_FillValue": -1,
    }
)
ds

<xarray.Dataset>
Dimensions:     (face: 2, nmax_face: 4, node: 6)
Coordinates:
    node_x      (node) float64 0.0 10.0 10.0 0.0 20.0 20.0
    node_y      (node) float64 0.0 0.0 10.0 10.0 0.0 10.0
    face_x      (face) float64 5.0 15.0
    face_y      (face) float64 5.0 5.0
Dimensions without coordinates: face, nmax_face, node
Data variables:
    mesh2d      int64 0
    face_nodes  (face, nmax_face) int64 0 1 2 3 1 4 5 -1

In [5]:
exods=xr.load_dataset("hex_2x2x2_ss.exo")
exods

<xarray.Dataset>
Dimensions:       (four: 4, num_att_in_blk1: 1, num_dim: 3, num_el_blk: 1, num_el_in_blk1: 1, num_nod_ns1: 8, num_nod_ns2: 4, num_nod_ns3: 4, num_nod_ns4: 4, num_nod_ns5: 4, num_nod_ns6: 4, num_nod_ns7: 4, num_nod_per_el1: 8, num_node_sets: 7, num_nodes: 8, num_qa_rec: 1, num_side_sets: 7, num_side_ss1: 6, num_side_ss2: 1, num_side_ss3: 1, num_side_ss4: 1, num_side_ss5: 1, num_side_ss6: 1, num_side_ss7: 1, time_step: 0)
Dimensions without coordinates: four, num_att_in_blk1, num_dim, num_el_blk, num_el_in_blk1, num_nod_ns1, num_nod_ns2, num_nod_ns3, num_nod_ns4, num_nod_ns5, num_nod_ns6, num_nod_ns7, num_nod_per_el1, num_node_sets, num_nodes, num_qa_rec, num_side_sets, num_side_ss1, num_side_ss2, num_side_ss3, num_side_ss4, num_side_ss5, num_side_ss6, num_side_ss7, time_step
Data variables:
    time_whole    (time_step) float64 
    eb_status     (num_el_blk) int32 1
    eb_prop1      (num_el_blk) int32 30000
    ns_status     (num_node_sets) int32 1 1 1 1 1 1 1
    ns_prop1      (num_node_sets) int32 1 101 102 103 104 105 106
    ss_status     (num_side_sets) int32 1 1 1 1 1 1 1
    ss_prop1      (num_side_sets) int32 1 101 102 103 104 105 106
    coordx        (num_nodes) float64 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0
    coordy        (num_nodes) float64 0.0 0.0 1.0 1.0 0.0 0.0 1.0 1.0
    coordz        (num_nodes) float64 0.0 0.0 0.0 0.0 1.0 1.0 1.0 1.0
    eb_names      (num_el_blk) |S33 b''
    ns_names      (num_node_sets) |S33 b'' b'' b'' b'' b'' b'' b''
    ss_names      (num_side_sets) |S33 b'' b'' b'' b'' b'' b'' b''
    coor_names    (num_dim) |S33 b'' b'' b''
    qa_records    (num_qa_rec, four) |S33 b'mesh2' b'probname' b'Today' b'Time'
    attrib1       (num_el_in_blk1, num_att_in_blk1) float64 0.0
    attrib_name1  (num_att_in_blk1) |S33 b''
    connect1      (num_el_in_blk1, num_nod_per_el1) int32 1 2 4 3 5 6 8 7
    node_ns1      (num_nod_ns1) int32 1 3 4 2 5 6 8 7
    node_ns2      (num_nod_ns2) int32 1 3 4 2
    node_ns3      (num_nod_ns3) int32 5 6 8 7
    node_ns4      (num_nod_ns4) int32 1 2 6 5
    node_ns5      (num_nod_ns5) int32 2 4 8 6
    node_ns6      (num_nod_ns6) int32 4 3 7 8
    node_ns7      (num_nod_ns7) int32 1 5 7 3
    elem_ss1      (num_side_ss1) int32 1 1 1 1 1 1
    side_ss1      (num_side_ss1) int32 5 6 1 2 3 4
    elem_ss2      (num_side_ss2) int32 1
    side_ss2      (num_side_ss2) int32 5
    elem_ss3      (num_side_ss3) int32 1
    side_ss3      (num_side_ss3) int32 6
    elem_ss4      (num_side_ss4) int32 1
    side_ss4      (num_side_ss4) int32 1
    elem_ss5      (num_side_ss5) int32 1
    side_ss5      (num_side_ss5) int32 2
    elem_ss6      (num_side_ss6) int32 1
    side_ss6      (num_side_ss6) int32 3
    elem_ss7      (num_side_ss7) int32 1
    side_ss7      (num_side_ss7) int32 4
Attributes:
    api_version:               4.93
    version:                   4.93
    floating_point_word_size:  8
    file_size:                 1
    title:                     Lagrit-to-ExodusII

In [6]:
exods.num_dim.values

array([0, 1, 2])

In [7]:
exods.coordx.values

array([0., 1., 0., 1., 0., 1., 0., 1.])

In [8]:
exods.connect1

<xarray.DataArray 'connect1' (num_el_in_blk1: 1, num_nod_per_el1: 8)>
array([[1, 2, 4, 3, 5, 6, 8, 7]], dtype=int32)
Dimensions without coordinates: num_el_in_blk1, num_nod_per_el1
Attributes:
    elem_type:  HEX

In [9]:
exods.node_ns1.values

array([1, 3, 4, 2, 5, 6, 8, 7], dtype=int32)

In [10]:
exods.node_ns2.values

array([1, 3, 4, 2], dtype=int32)

In [11]:
exods.node_ns7

<xarray.DataArray 'node_ns7' (num_nod_ns7: 4)>
array([1, 5, 7, 3], dtype=int32)
Dimensions without coordinates: num_nod_ns7

exods.elem_ss3.values

In [12]:
# might need pip install netcdf4
cexo = xr.load_dataset("outCSne8.g")
cexo

<xarray.Dataset>
Dimensions:     (four: 4, num_att_in_blk1: 1, num_dim: 3, num_el_blk: 1, num_el_in_blk1: 384, num_nod_per_el1: 4, num_nodes: 386, num_qa_rec: 1, time_step: 0)
Dimensions without coordinates: four, num_att_in_blk1, num_dim, num_el_blk, num_el_in_blk1, num_nod_per_el1, num_nodes, num_qa_rec, time_step
Data variables:
    time_whole  (time_step) float64 
    qa_records  (num_qa_rec, four) |S33 b'Tempest' b'14.0' ... b'13:08:22'
    coor_names  (num_dim) |S33 b'x' b'y' b'z'
    eb_names    (num_el_blk) |S33 b''
    eb_status   (num_el_blk) int32 1
    eb_prop1    (num_el_blk) int32 1
    attrib1     (num_el_in_blk1, num_att_in_blk1) float64 9.969e+36 ... 9.969...
    connect1    (num_el_in_blk1, num_nod_per_el1) int32 1 9 93 37 ... 78 7 79
    global_id1  (num_el_in_blk1) int32 1 2 3 4 5 6 7 ... 379 380 381 382 383 384
    edge_type1  (num_el_in_blk1, num_nod_per_el1) int32 0 0 0 0 0 ... 0 0 0 0 0
    coord       (num_dim, num_nodes) float64 0.5774 0.5774 ... 0.7862 0.7268
Attributes:
    api_version:               5.0
    version:                   5.0
    floating_point_word_size:  8
    file_size:                 0
    title:                     tempest(outCSne8.g) 08/20/2021: 13:08:22

In [13]:
cexo.coord.values[1].size

386

In [14]:
scripds = xr.open_dataset("outCSne8.nc")
scripds

<xarray.Dataset>
Dimensions:          (grid_corners: 4, grid_rank: 1, grid_size: 384)
Dimensions without coordinates: grid_corners, grid_rank, grid_size
Data variables:
    grid_area        (grid_size) float64 ...
    grid_center_lat  (grid_size) float64 ...
    grid_center_lon  (grid_size) float64 ...
    grid_corner_lat  (grid_size, grid_corners) float64 ...
    grid_corner_lon  (grid_size, grid_corners) float64 ...
    grid_imask       (grid_size) int32 ...
    grid_dims        (grid_rank) int32 ...
Attributes:
    api_version:               5.0
    version:                   5.0
    floating_point_word_size:  8
    file_size:                 0

In [15]:
scripds.grid_center_lon.values[0]

320.49484877621154

In [16]:
scripds.coordx

AttributeError: 'Dataset' object has no attribute 'coordx'

In [ ]:
# use a library to read ugrid file https://github.com/nschloe/meshio
# ugrid reading is fairly straight forward or so it seems: 
# https://github.com/nschloe/meshio/blob/main/src/meshio/ugrid/_ugrid.py
# ds_ug = xr.open_dataset("sphere_mixed.1.lb8.ugrid")
# xarray cannot open ugrid file
import meshio
mesh = meshio.read("sphere_mixed.1.lb8.ugrid")
mesh

<meshio mesh object>
  Number of points: 3270
  Number of cells:
    triangle: 864
    tetra: 9072
    wedge: 3024
  Cell data: ugrid:ref

In [ ]:
mesh.write("sphere_mixed.1.lb8.exo")

In [ ]:
# now load this as an exodus file with xarray
ugrid_exo_ds = xr.open_dataset("sphere_mixed.1.lb8.exo")
ugrid_exo_ds

<xarray.Dataset>
Dimensions:     (num_dim: 3, num_el_blk: 3, num_el_in_blk1: 864, num_el_in_blk2: 9072, num_el_in_blk3: 3024, num_nod_per_el1: 3, num_nod_per_el2: 4, num_nod_per_el3: 6, num_nodes: 3270, time_step: 1)
Dimensions without coordinates: num_dim, num_el_blk, num_el_in_blk1, num_el_in_blk2, num_el_in_blk3, num_nod_per_el1, num_nod_per_el2, num_nod_per_el3, num_nodes, time_step
Data variables:
    time_whole  (time_step) float32 ...
    coor_names  (num_dim) |S33 ...
    coord       (num_dim, num_nodes) float64 ...
    eb_prop1    (num_el_blk) int32 ...
    connect1    (num_el_in_blk1, num_nod_per_el1) int32 ...
    connect2    (num_el_in_blk2, num_nod_per_el2) int32 ...
    connect3    (num_el_in_blk3, num_nod_per_el3) int32 ...
Attributes:
    title:                     Created by meshio v4.4.6, 2021-11-19T01:52:14....
    version:                   5.1
    api_version:               5.1
    floating_point_word_size:  8

In [ ]:
ugrid_exo_ds.coord

<xarray.DataArray 'coord' (num_dim: 3, num_nodes: 3270)>
array([[-5.000000e-01, -4.786055e-01, -4.786055e-01, ...,  2.956231e-01,
         3.684645e-01,  4.694956e-01],
       [-2.969236e-17,  7.234767e-02,  1.446953e-01, ...,  3.959419e-01,
         4.935019e-01,  6.288176e-01],
       [ 1.337313e-17,  1.253098e-01,  4.770621e-17, ...,  1.158330e+00,
         1.443743e+00,  1.839609e+00]])
Dimensions without coordinates: num_dim, num_nodes

In [ ]:
meshio_exo = meshio.read("outCSne8.g", file_format="exodus")

In [ ]:
meshio_exo.write("outCSne9.h5m")
# does not support quad elements for MOAB mesh
# https://github.com/nschloe/meshio/blob/main/src/meshio/h5m/_h5m.py#L226
# only vertices are written

In [19]:
ds_rll = xr.open_dataset("./outRLL1deg.ug")
ds_rll

<xarray.Dataset>
Dimensions:           (nMaxMesh2_face_nodes: 4, nMesh2_face: 64800, nMesh2_node: 64442)
Dimensions without coordinates: nMaxMesh2_face_nodes, nMesh2_face, nMesh2_node
Data variables:
    Mesh2             int32 ...
    Mesh2_face_nodes  (nMesh2_face, nMaxMesh2_face_nodes) float64 ...
    Mesh2_node_x      (nMesh2_node) float64 ...
    Mesh2_node_y      (nMesh2_node) float64 ...

In [20]:
ds_rll10deg = xr.open_dataset("./ov_RLL10deg_CSne4.ug")
ds_rll10deg

<xarray.Dataset>
Dimensions:           (nMaxMesh2_face_nodes: 5, nMesh2_face: 856, nMesh2_node: 683)
Dimensions without coordinates: nMaxMesh2_face_nodes, nMesh2_face, nMesh2_node
Data variables:
    Mesh2             int32 ...
    Mesh2_face_nodes  (nMesh2_face, nMaxMesh2_face_nodes) float64 ...
    Mesh2_node_x      (nMesh2_node) float64 ...
    Mesh2_node_y      (nMesh2_node) float64 ...

In [21]:
ds_out30 = xr.open_dataset("outCSne30.ug")
ds_out30

<xarray.Dataset>
Dimensions:           (nMaxMesh2_face_nodes: 4, nMesh2_face: 5400, nMesh2_node: 5402)
Dimensions without coordinates: nMaxMesh2_face_nodes, nMesh2_face, nMesh2_node
Data variables:
    Mesh2             int32 ...
    Mesh2_face_nodes  (nMesh2_face, nMaxMesh2_face_nodes) float64 ...
    Mesh2_node_x      (nMesh2_node) float64 ...
    Mesh2_node_y      (nMesh2_node) float64 ...